import { useEffect, useRef, useState } from 'react'
import { categories } from './faqCategories.js'

const WELCOME = {
  role: 'assistant',
  category: 'GEN-501',
  text:
    "Welcome to the Registry. I'm the Caleb University student help desk — ask me about admissions, fees, course registration, exams, or campus life. Tap a code on the left or type your own question below.",
  time: timestamp(),
}

function timestamp() {
  return new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

export default function App() {
  const [messages, setMessages] = useState([WELCOME])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [activeCategory, setActiveCategory] = useState(null)
  const threadEndRef = useRef(null)

  useEffect(() => {
    threadEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, loading])

  async function sendMessage(text) {
    const question = text.trim()
    if (!question || loading) return

    const userMsg = { role: 'user', text: question, time: timestamp() }
    setMessages((prev) => [...prev, userMsg])
    setInput('')
    setLoading(true)

    try {
      const res = await fetch('/.netlify/functions/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: question,
          history: messages.slice(-8).map((m) => ({ role: m.role, text: m.text })),
        }),
      })

      if (!res.ok) throw new Error('Request failed')
      const data = await res.json()

      setMessages((prev) => [
        ...prev,
        {
          role: 'assistant',
          text: data.reply,
          category: data.category || 'GEN-501',
          time: timestamp(),
        },
      ])
    } catch (err) {
      setMessages((prev) => [
        ...prev,
        {
          role: 'assistant',
          text:
            "The registry desk couldn't process that — the connection to the API may be down, or the function key isn't set yet. Check the README for setup steps.",
          category: 'GEN-501',
          time: timestamp(),
          isError: true,
        },
      ])
    } finally {
      setLoading(false)
    }
  }

  function handleSubmit(e) {
    e.preventDefault()
    sendMessage(input)
  }

  return (
    <div className="app">
      <aside className="ledger">
        <div className="ledger-brand">
          <span className="ledger-mark">CUL</span>
          <div>
            <h1>The Registry</h1>
            <p>Student FAQ Desk</p>
          </div>
        </div>

        <nav className="ledger-categories">
          <p className="ledger-heading">Browse by code</p>
          {categories.map((cat) => (
            <div
              key={cat.code}
              className={`ledger-cat ${activeCategory === cat.code ? 'is-open' : ''}`}
            >
              <button
                className="ledger-cat-toggle"
                onClick={() =>
                  setActiveCategory(activeCategory === cat.code ? null : cat.code)
                }
              >
                <span className="code">{cat.code}</span>
                <span className="label">{cat.label}</span>
              </button>
              {activeCategory === cat.code && (
                <ul className="ledger-prompts">
                  {cat.prompts.map((p) => (
                    <li key={p}>
                      <button onClick={() => sendMessage(p)}>{p}</button>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </nav>

        <p className="ledger-footnote">
          Answers are generated by AI and grounded in the registry's notes. Always confirm
          deadlines and fees with the official school portal.
        </p>
      </aside>

      <main className="thread-panel">
        <header className="thread-header">
          <h2>Ask the Registry</h2>
          <span className="thread-status">{loading ? 'typing…' : 'online'}</span>
        </header>

        <div className="thread">
          {messages.map((m, i) => (
            <div key={i} className={`msg-row ${m.role}`}>
              {m.role === 'assistant' && (
                <span className="stamp" aria-hidden="true">
                  <span className="stamp-code">{m.category}</span>
                  <span className="stamp-label">verified</span>
                </span>
              )}
              <div className={`bubble ${m.role} ${m.isError ? 'is-error' : ''}`}>
                <p>{m.text}</p>
                <time>{m.time}</time>
              </div>
            </div>
          ))}
          {loading && (
            <div className="msg-row assistant">
              <span className="stamp stamp-pending" aria-hidden="true">
                <span className="stamp-code">…</span>
              </span>
              <div className="bubble assistant is-typing">
                <span className="dot" />
                <span className="dot" />
                <span className="dot" />
              </div>
            </div>
          )}
          <div ref={threadEndRef} />
        </div>

        <form className="composer" onSubmit={handleSubmit}>
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Type a question for the registry…"
            aria-label="Ask a question"
          />
          <button type="submit" disabled={loading || !input.trim()}>
            Ask
          </button>
        </form>
      </main>
    </div>
  )
}
